# -*- coding: utf-8 -*-
"""ejercicio_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mbQ20JBcDzPHI1Y_S1nj4JPKlJe9xHJO

Una panadería vende barras de pan a 3.49€ cada una. El pan que no es el día tiene un descuento del 60%. Escribe un programa que comience leyendo el número de barras vendidas que no son del día. Después tu programa debe mostrar el precio habitual de una barra de pan, el descuento que se le hace por no ser fresca y el coste final total.
"""

#Matias Tapia

""" Escribir un programa que le pregunte al usuario una cantidad a invertir, el interés porcentual anual y el número de años, y muestre por pantalla el capital obtenido en la inversión redondeado a dos decimales.
 
"""

#Matias Tapia

#se le indica al usuario ingrese los datos
capital_a_invertir = float(input("ingrese capital a invertir: "))
interes = float(input("ingrese porcentual anual: "))
número_años = float(input("ingrese número de años: "))

#calculo de formula, donde pow es para la potencia de numero de años
auxiliar_formula = ((interes / 100) + 1)
formula = capital_a_invertir * pow(auxiliar_formula, número_años)
formula = round(formula, 2)

#resultado del capital obtenido
print("El capital obtenido seria: " + str(formula))